### ISSUE TITLE
Bug Report Chat Command

### ISSUE THREAD

**Issue by SHOKITO12** [Dans-Plugins/Medieval-Factions#1813]
Hello good morning, afternoon or evening The bug I found is not a bug that affects too much because it is a bug of another plugin I would like you to tell me what I can do etc. The plugin is GeyserMC I know you will tell me that I am not responsible for that, here I send you some evidence of the bug. Thank you very much for reading me. 
![Screenshot_20241116-121732](https://github.com/user-attachments/assets/7bbe4150-575e-4f9f-ad03-97165f86f5d3)

**Comment by dmccoystephenson** [comment]
Hi @SHOKITO12,  

Thanks for reaching out and providing details about the issue! While it seems this bug is related to GeyserMC, I appreciate you bringing it to our attention. Unfortunately, we don't manage that plugin directly, so the best course of action would be to report it to their team.  

That said, if you notice any interaction between *Medieval Factions* and GeyserMC that could be improved, feel free to share more specifics, and we’ll look into it. Thanks again!
